### ISSUE TITLE
Dependency issues - can't install

### ISSUE THREAD

**Issue by alicam** [djboris88/timber-debugger#1]
Composer breaks as follows:

![image](https://user-images.githubusercontent.com/44537/70587974-83432100-1c1f-11ea-9428-9cc73e4da168.png)

Not sure how to fix that one!

Can you investigate?

Thanks!

**Comment by djboris88** [comment]
I have updated the `package.json` and bumped the dependency versions. Can you please try again?

**Comment by djboris88** [comment]
Closed due to inactivity. Feel free to reopen if the issue occurs again.
